import type { VisualNovelEvent } from "../../model.ts";

export const gateEvents: VisualNovelEvent[] = [
  { type: "background", asset: "background.gate-empty", transition: "fade" },
  { type: "cg", asset: "cg.scene.gate" },
  { type: "narration", text: "黑风呼啸，暴雨倾盆。荒原上的蛊市早已散尽，冷风里带着淡淡腥臭。\n\n古老的石门前，六名散修各自站定，气息强弱不一。雨点打在护体光罩与蓑衣上，噼啪作响。", mode: "center" },
  { type: "character", action: "show", character: "qiao-wujiu", position: "center", expression: "neutral" },
  { type: "narration", text: "为首的中年男子叫乔无咎，穿着一身不起眼的灰袍。他神色平静，从袖中取出一张泛黄的兽皮残图，指尖渡入一缕真元。图上的猩红标记随即亮起。" },
  { type: "dialogue", speaker: "qiao-wujiu", displayName: "乔无咎", text: "诸位道友，老夫耗费数载方才查实，这荒原地下埋着的，乃是数百年前一位五转蛊修的坐化洞府。", expression: "neutral", position: "center" },
  { type: "narration", text: "雨声中多了几声沉重的呼吸。若能得到五转蛊修留下的秘宝与本命蛊，在场这些苦苦求道的散修，或许便能换一种活法。" },
  { type: "dialogue", speaker: "qiao-wujiu", displayName: "乔无咎", text: "在蛊道一途，能炼出五转本命蛊者无一不是手段通天之人。老夫按约定带路，入内后若有所得，见者有份。", expression: "neutral", position: "center" },
  { type: "character", action: "hide", character: "qiao-wujiu" },
  { type: "narration", text: "你站在队伍后方，暗中运转敛气之术，右手按着袖里的祖传旧玉。\n\n旧玉平日冷得像铁，此刻却在掌心发烫，一下下轻颤。石门深处，一股与它同源的古老气息正缓缓苏醒。" },
  { type: "character", action: "show", character: "zhao-li", position: "left", expression: "neutral" },
  { type: "narration", text: "斜前方，一名倚着青石的少年忽然冷笑。他唇红齿白，嗓音却沙哑得像个老者。指尖那只猩红蛊虫伸出口器，吮吸着雨幕中稀薄的血气。" },
  { type: "character", action: "expression", character: "zhao-li", position: "left", expression: "amused" },
  { type: "dialogue", speaker: "zhao-li", displayName: "赵黎", text: "见者有份？乔道友这话未免太轻巧了。", expression: "amused", position: "left" },
  { type: "character", action: "show", character: "ji-qinghan", asset: "character.ji-qinghan.neutral", position: "right", expression: "neutral" },
  { type: "narration", text: "数尺外，白衣女修纪清寒抱剑站在雨中。剑意逼人，无人靠近。雨水沿鬓角滑入领口，她也不抬手去拭，神色始终冷淡。" },
  { type: "character", action: "hide", character: "zhao-li" },
  { type: "character", action: "hide", character: "ji-qinghan" },
  { type: "character", action: "show", character: "xue-feng", position: "left", expression: "neutral" },
  { type: "narration", text: "圆脸汉子薛逢笑着打圆场，那双细长的三角眼却不时扫过众人的储物袋与要害。" },
  { type: "character", action: "expression", character: "xue-feng", position: "left", expression: "smiling" },
  { type: "dialogue", speaker: "xue-feng", displayName: "薛逢", text: "嘿嘿，我等散修在外讨生活本就艰难，进了洞府禁制，诸位可要齐心协力才是。", expression: "smiling", position: "left" },
  { type: "character", action: "hide", character: "xue-feng" },
  { type: "character", action: "show", character: "su-ying", position: "right", expression: "neutral" },
  { type: "narration", text: "你侧前方，少女苏莹低着头，用指尖在泥里描摹石门上的蛊纹，口中念念有词。她似乎认得这道禁制。" },
  { type: "character", action: "expression", character: "su-ying", position: "right", expression: "wary" },
  { type: "narration", text: "察觉众人的目光后，她立刻护住泥地上尚未画完的纹路，戒备地退开半步。" },
  { type: "character", action: "hide", character: "su-ying" },
  { type: "character", action: "show", character: "qiao-wujiu", position: "center", expression: "neutral" },
  { type: "dialogue", speaker: "qiao-wujiu", displayName: "乔无咎", text: "时候不早，此时正是子夜禁制最弱之际。此去生死难料，诸位自便吧。", expression: "neutral", position: "center" },
  { type: "narration", text: "话音未落，乔无咎已撑起一道灰光，闪身没入漆黑的石门。" },
  { type: "character", action: "hide", character: "qiao-wujiu" },
  { type: "character", action: "show", character: "zhao-li", position: "left", expression: "amused" },
  { type: "narration", text: "赵黎不屑地冷笑一声，跟了进去。\n\n你按紧发烫的旧玉，运起真元，抬脚跟上。" },
];

export const rainMarkEvents: VisualNovelEvent[] = [
  { type: "background", asset: "background.tomb-gate", transition: "fade" },
  { type: "narration", text: "跨过石门，一条狭长石阶盘曲向下，通往湿冷的地底。\n\n洞里闷着腥臭，门外的雨水沿陡阶流下，冲开积年的黑黏浮泥。\n\n借着洞壁上时明时暗的磷光，你看见泥下露出几道暗红纹路。它们盘曲交错，形如蜈蚣百足。" },
  { type: "character", action: "show", character: "ji-qinghan", asset: "character.ji-qinghan.alert", position: "right", expression: "alert" },
  { type: "narration", text: "纪清寒凝神看过石阶，周身灵气一荡，化作一道白虹掠出。靴底轻点几块阶石，她便安然落在数丈外的拐弯处。\n\n她带起的风扫开了阶面泥沙。你走在队伍后方，留意到暗红蛊纹的交汇处藏着一圈圈针眼大小的细孔。孔内泛着幽绿冷光，淬的是见血封喉的毒。" },
  { type: "narration", text: "纪清寒落脚极轻，方才没有触动机关。\n\n薛逢笑着跟在她后面，步子却重得多。他抬起右脚，正要踩上那块布满毒针暗孔的石阶。\n\n你收紧袖中的手指，望着他将要落下的脚。" },
];

export const bloodThresholdEvents: VisualNovelEvent[] = [
  { type: "background", asset: "background.blood-threshold-empty", transition: "fade" },
  { type: "cg", asset: "cg.scene.bloodThreshold" },
  { type: "narration", text: "石阶盘旋向下，延伸了约莫三四十丈。越往深处，泥腐与腥膻之气越重。\n\n甬道口上方斜悬着一道数丈高的万斤石闸，门槛后的通道只容一人弯腰通过。乔无咎、赵黎、薛逢和苏莹已经先后入内，身影消失在黑暗里。\n\n石阶尽头只剩你与纪清寒，相隔数尺，一前一后走向石闸。\n\n你将感知收在周身三尺之内，放慢脚步，留意她的落脚处与门框两侧。" },
  { type: "character", action: "show", character: "ji-qinghan", position: "left", expression: "alert" },
  { type: "narration", text: "纪清寒刚跨过青石门槛，脚下蜈蚣般的暗红蛊纹便爆出血光。\n\n山体深处一声闷响，锁住石闸的机括松脱。万斤巨石沿滑轨直坠，压向门槛！\n\n两侧门框同时弹开机括，四条尺许长的赤褐毒蛊露出獠牙，直扑纪清寒的面门与心口。\n\n纪清寒拔剑，雪白剑气扫过门前。三条毒蛊应声断裂，血水溅落石阶。第四条却藏在血雾后，贴着门框绕到她身后，缠住执剑的手腕与剑柄，尾端倒钩仍扣在门框石孔中。虫躯收紧，将剑锋扯向地面。\n\n石闸下坠的风吹得衣袍猎猎作响。纪清寒被拖在门槛处，眼中闪过惊慌，咬牙喊道。" },
  { type: "dialogue", speaker: "ji-qinghan", displayName: "纪清寒", text: "石闸要落下了！", expression: "alert", position: "left" },
];
